@url ="http://localhost:5000/"


### Signup
POST http://localhost:5000/register/admin HTTP/1.1
Content-Type: application/json

{
    "email": "linda.boateng@amalitech.org",
    "password": "123456"
}


####login
POST http://localhost:5000/login/admin HTTP/1.1
Content-Type: application/json

{
     "email": "linda.boateng@amalitech.org",
    "password": "123456"
}


####
GET http://localhost:3000/admin/downloads HTTP/1.1