@url ="https://lizzy-files-f7a38d64c9a1.herokuapp.com/""

###searching for a file
GET https://lizzy-files-f7a38d64c9a1.herokuapp.com/search/


##### files feed
GET https://lizzy-files-f7a38d64c9a1.herokuapp.com/home


###sending file email
POST https://lizzy-files-f7a38d64c9a1.herokuapp.com/sendfile
Content-Type:application/json

{
    "email":"millicent.opoku@amalitech.org",
    "filename":"Screenshot_2023.04.07_00.34.33.749.png"
}

#####downloading
GET https://lizzy-files-f7a38d64c9a1.herokuapp.com/download/sachet.pdf


####
GET https://lizzy-files-f7a38d64c9a1.herokuapp.com/admin/downloads

####
GET https://lizzy-files-f7a38d64c9a1.herokuapp.com/preview/Man_United.png HTTP/1.1