@url ="http://localhost:5000/"


### Signup
POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{
    "email": "fileserver353@gmail.com",
    "password": "12345"
}


####login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
     "email": "linda.boateng@amalitech.org",
    "password": "12345"
}
