@url ="http://localhost:3000"


### Signup
POST http://localhost:3000/signup 
Content-Type: application/json

{
    "email": "lindapomaa27@gmail.com",
    "password": "111111"
}


####login
POST http://localhost:3000/login 
Content-Type: application/json

{
     "email": "lindapomaa27@gmail.com",
    "password": "111111"
}


####verifying
GET http://localhost:3000/user/verify/

###requesting for password reset
POST http://localhost:3000/user/passwordresetrequest HTTP/1.1
Content-Type:application/json

{
    "email":"lindapomaa27@gmail.com"
}


###setting new pasword
GET http://localhost:3000/user/passwordreset/6498e1dc08db3a1e80086b4b/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpbmRhcG9tYWEyN0BnbWFpbC5jb20iLCJpYXQiOjE2OTUyMzE3MTgsImV4cCI6MTY5NTIzMzUxOH0.KCdN1vkMXq3O2qJA5ATp533rNxBMIBQMEJISZp_4N28
Content-Type: application/json

{
    "password":"333333"
}


#####
 POST  http://localhost:3000/login
 Content-Type: application/json
 
 {
     "email": "linda.boateng@amalitech.org",
    "password": "333333"
}

#######
 GET http://localhost:3000/home


 #####
 GET http://localhost:3000/logins 


  #####
 GET http://localhost:3000/register