@url ="http://localhost:5000/"


### Signup
POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{
    "email": "lindapomaa27@gmail.com",
    "password": "111111"
}


####login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
     "email": "linda.boateng@amalitech.org",
    "password": "333333"
}


####verifying
GET http://localhost:5000/user/verify/643854cf32ce93869bada76d/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpbmRhcG9tYWEyN0BnbWFpbC5jb20iLCJpYXQiOjE2ODE0MTMzMjcsImV4cCI6MTY4MTQ5OTcyN30.xoiBCcy-xV6o7sCcVwHk7Qo9WBKXuQgy9FjkpMhO0O4/ HTTP/1.1

###requesting for password reset
POST http://localhost:5000/user/passwordresetrequest HTTP/1.1
Content-Type:application/json

{
    "email":"linda.boateng@amalitech.org"
}


###setting new pasword
GET http://localhost:5000/user/passwordreset/6436056afde08114ee929c40/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpbmRhLmJvYXRlbmdAYW1hbGl0ZWNoLm9yZyIsImlhdCI6MTY4NzEyMzcxNCwiZXhwIjoxNjg3MTI1NTE0fQ.KFY9U9DBI4yZxNZfhik6QAuLPz0gFjt_eqMtITuBxes HTTP/1.1
Content-Type: application/json

{
    "password":"333333"
}